# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GeekForged
title-part-one: Geek
title-part-two: Forged
description: > # this means to ignore newlines until "baseurl:"
  I'm a generalist Geek who loves to make, break and tinker with things.
  I hope to teach and inspire you to do the same, creating some truly amazing things along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geekforged.com" # the base hostname & protocol for your site
twitter_username: GeekForged
github_username: GeekForged
youtube_username: geekforged

# Build settings
markdown: kramdown
